name = "Robust"
license = "MIT"
baseurl = "https://libmb.github.io"
languageCode = "en-us"
title = "Shelters House"
theme = "hugo_theme_robust"

[author]
  name = "Shelter B"
  # homepage = "https://yet.unresolved.xyz/"
